### ISSUE TITLE
More tweets than the account's tweet count 

### ISSUE THREAD

**Issue by alexhoneker** [DocNow/twarc-csv#17]
Hi! Thanks Igor for the quick reply to my issue #16. I was able to find a workaround to get what I wanted (keep original tweets which were retweeted but exclude truncated retweets) and get German characters and emojis. However, I get more tweets than the account's tweet count. Do you have any idea what I may be missing here? Below is my code (probably very long and inefficient, so apologies!): 

1. Download full archive 
`!twarc2 search "(from:volkspartei)" --archive > OVP.jsonl` 

2. Convert JSONL file to CSV 
`!twarc2 csv OVP.jsonl OVP.csv`

3. Convert to data frame to delete blank lines  
`OVP = pd.read_csv("OVP.csv")`

4. Delete rows with blank values in "text" 
`OVP = OVP.dropna(axis=0, subset=['text'])`

5. Filter "text" column starting with "RT" to exclude truncated retweets and keep original RT tweet 
`OVP = OVP[~OVP.text.str.startswith("RT")]`

6. Keep only selected columns 
```
OVP = OVP[['author.created_at','author.name','author.username','created_at','text','type',
                  'public_metrics.like_count','public_metrics.retweet_count','public_metrics.quote_count',
                  'public_metrics.reply_count','id','conversation_id','lang','author.public_metrics.followers_count',
                  'author.public_metrics.following_count','author.public_metrics.listed_count',
                   'author.public_metrics.tweet_count']]
``` 

7. Rename columns 
```
OVP = OVP.rename(columns={'author.created_at': 'account_created_at', 'author.name': 'account_name',
                                   'author.username': 'username', 'public_metrics.like_count': 'like_count', 
                                   'public_metrics.retweet_count': 'retweet_count', 'public_metrics.quote_count': 
                                   'quote_count', 'public_metrics.reply_count': 'reply_count', 
                                   'author.public_metrics.followers_count': 'account_followers', 
                                   'author.public_metrics.following_count' : 'account_following',
                                   'author.public_metrics.listed_count': 'account_listed', 
                                   'author.public_metrics.tweet_count': 'account_tweet_count'})
```

8. Reset index number after dropping NA rows 
`OVP = OVP.reset_index(drop=True)`

9. Save back to CSV 
`OVP.to_csv("OVP_1.csv")`

As you can see, the final file has a total of 12186 tweets, whereas the account's tweet count is only 11917. Do you have any idea why I end up with more tweets? If all truncated Retweets begin with "RT", then my solution above should work, right? 

Thanks a lot!

**Comment by igorbrigadir** [comment]
Without looking at the data, I suspect it's still `referenced_tweets` - since the csv conversion includes all types of referenced tweets inline, it will also include quoted tweets and replied to tweets - i think i'll keep this issueopen to remind myself to put in an option to make the `--inline-referenced-tweets` granular - so you can pick retweets, quotes, replies, etc.

**Comment by igorbrigadir** [comment]
I updated how referenced tweets are handled and it should be better in the new version.

```
pip3 install --upgrade twarc-csv
```

Please reopen if there's still discrepancies when using `--no-inline-referenced-tweets` (this should match the exact count and ignore referenced tweets) I will follow up with more options for referenced tweets in #21
