### ISSUE TITLE
0% JSON to CSV 

### ISSUE THREAD

**Issue by Tom1316** [DocNow/twarc-csv#23]
When using twarc2 csv tweets.jsonl tweets.csv # convert to CSV

It loads the JSONL and runs the script at 0%:

  0%|                                                                                      | 0.00/2.72M [00:00<?, ?B/s]

**Comment by igorbrigadir** [comment]
How big is the `tweets.jsonl` file and what command generated this file?

**Comment by Tom1316** [comment]
The JSONL is 2783KBS and the command was: 

twarc2 csv test.jsonl tweets.csv # convert to CSV.

**Comment by igorbrigadir** [comment]
oh, sorry, i meant - what was the command that wrote `test.jsonl` - was it `twarc2 search`? Can compress and attach this `test.jsonl` file here?

**Comment by Tom1316** [comment]
No worries! I hydrated the tweets using: twarc hydrate test.txt > test.jsonl. I'm hoping to use the Twarc cmd to hydrate a large JSONL of roughly 1M Tweets. The test files is a smaller file of 500 Tweets. 

I think publicly publishing the JSON break Twitter's T&C for privacy, I can email it to you if that works?

**Comment by igorbrigadir** [comment]
Sure - igor.brigadir at gmail.com will work

**Comment by igorbrigadir** [comment]
I never found the tweets in case you sent them, but I released a new version, so try again after:

```
pip3 install --upgrade twarc-csv
```

Please reopen if it's still an issue.
