### ISSUE TITLE
mangled CSV file

### ISSUE THREAD

**Issue by suvinasingal** [DocNow/twarc-csv#28]
[output_Singal.csv.zip](https://github.com/DocNow/twarc-csv/files/6835707/output_Singal.csv.zip)

**Comment by igorbrigadir** [comment]
Couldn't find anything wrong code wise, so feel free to follow up here if still getting errors opening: https://twittercommunity.com/t/converting-json-to-csv-to-save-tweets-but-getting-mangled-text/156847/11?u=igorbrigadir
