### ISSUE TITLE
entities.urls missing for referenced tweets

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc-csv#33]
It appears that referenced tweets don't have their URLs pulled over into their rows in the CSV? This came up in https://github.com/DocNow/twarc/issues/538 

```
$ twarc2 tweet 1438733968287977476 | twarc2 csv - > tweet.csv
$ xsv select id,entities.urls tweet.csv
id,entities.urls
1438486160867745801,
1438733968287977476,"[{""start"": 162, ""end"": 185, ""url"": ""https://t.co/wRfX2O9S7W"", ""expanded_url"": ""https://twitter.com/dereckapurnell/status/1438486160867745801"", ""display_url"": ""twitter.com/dereckapurnell\u2026""}]"
```

**Comment by edsu** [comment]
Actually that was a bad example because the quoted tweet didn't have a URL in it. It turns out that it is working:

```
twarc2 tweet 1437941918055366658 | twarc2 csv - > tweet.csv
➜  ~ xsv select id,entities.urls tweet.csv                     
id,entities.urls
1437762679884722184,"[{""start"": 256, ""end"": 279, ""url"": ""https://t.co/0Rm2r6nJ5g"", ""expanded_url"": ""http://ow.ly/3HR550G9CCX"", ""display_url"": ""ow.ly/3HR550G9CCX"", ""images"": [{""url"": ""https://pbs.twimg.com/news_img/1437762683584065545/vVQgFScz?format=jpg&name=orig"", ""width"": 480, ""height"": 360}, {""url"": ""https://pbs.twimg.com/news_img/1437762683584065545/vVQgFScz?format=jpg&name=150x150"", ""width"": 150, ""height"": 150}], ""status"": 200, ""title"": ""The costs and benefits of restoring a continent's terrestrial ecosystems"", ""description"": ""With growing international restoration commitments, governments and environmental organisations need methods to plan and budget their commitments. Here, we present a systematic approach to determine ..."", ""unwound_url"": ""https://besjournals.onlinelibrary.wiley.com/doi/10.1111/1365-2664.14008""}, {""start"": 280, ""end"": 303, ""url"": ""https://t.co/XAXdGf7S0w"", ""expanded_url"": ""https://twitter.com/JAppliedEcology/status/1437762679884722184/photo/1"", ""display_url"": ""pic.twitter.com/XAXdGf7S0w""}]"
1437941918055366658,"[{""start"": 281, ""end"": 304, ""url"": ""https://t.co/c2ceG0klFr"", ""expanded_url"": ""https://twitter.com/JAppliedEcology/status/1437762679884722184"", ""display_url"": ""twitter.com/JAppliedEcolog\u2026""}]"
```

**Comment by igorbrigadir** [comment]
I'm inclined to agree - the referenced tweets inline with result tweets are causing more confusion than it's worth.

As for the URLs - i'm not sure i understand the issue - some of this is on the API side, and if the data isn't in the JSON there's nothing we can do - what's the ideal output of that? how would the urls be represented in the CSV? maybe there's a better way we can do this

**Comment by edsu** [comment]
Yeah, obviously we are limited to what's available in the JSON. Do the URL expansions apply to referenced tweets too? I think we can close this if we are moving to having inlining be off by default. People who turn it on should be better able to interpret the results I think.

**Comment by igorbrigadir** [comment]
I'm gonna make some more changes to how retweets and replies and users are too - which may simplify things - I'll post some examples shortly!

**Comment by numeroteca** [comment]
> As for the URLs - i'm not sure i understand the issue - some of this is on the API side, and if the data isn't in the JSON there's nothing we can do 

I don't know if I understood well. In the downloaded json the full text of the RT is available, and the URL also in: referenced_tweets > referenced_tweets > entitites > urls > expanded_url

> what's the ideal output of that? how would the urls be represented in the CSV?

I can imagine different solutions:

- the text of the original tweet is rewritten in a new field with the expanded_url(s).
- create a new column in the CSV that has the link included in the tweet or in the RT. I don't have a definitive solution when there are two or more links (URL in the tweet + URL of the RT + URL in the RT). 

I see problems with RT and cited tweets, which make them more difficult to transform to the bidimensional. This would be what I'd expect to see in the text and urls field in the csv:

`text`
- A tweet with URL: Bla bla bla archive.org
- A simple RT: RT @user bla bla archive.org
- A cited RT: ble ble ble RT @user bla bla archive.org
- A cited RT with URL: ble ble ble news.docnow.io RT @user bla bla archive.org

`urls`
- A tweet with URL: archive.org
- A simple RT:  archive.org OR "linktotweet;arcive.org"
- A cited RT: archive.org OR "linktotweet;arcive.org"
- A cited RT with URL: "news.docnow.io;archive.org" OR "news.docnow.io;linktotweet;archive.org"

Not sure if there should be a link to the RT or reserve for it a special column.

A semicolon separated URL list would be easy to work with.

**Comment by igorbrigadir** [comment]
Thanks! This helps a lot.

I'm not sure about adding the urls to the text directly or from cited / quoted tweets - I think that might be even more confusing and make all the other entity and character counts invalid, but definitely going to separate out the referenced tweets into separate columns. Maybe the extra stuff can be optional with command line switches - I'll make a few versions to test!

**Comment by igorbrigadir** [comment]
Following on with this here: https://github.com/DocNow/twarc-csv/issues/30#issuecomment-926057179
