### ISSUE TITLE
Support large files

### ISSUE THREAD

**Issue by igorbrigadir** [DocNow/twarc-csv#4]
Right now it reads the entire result set into memory, which means it can't handle anything larger than a moderately sized dataset.

**Comment by igorbrigadir** [comment]
In the new version: 

I tried it with a GB file and it does a good job keeping the memory down. On my SSD i was getting 20MB/s processing speed, which seems reasonable to me. 

There is a new option `--batch-size` that defaults to 5000 tweets. The batch size determines the chunk size (in tweets) it will use to break up the parsing and writing.

There is a gotcha with processing in chunks: if the first 5000 tweets differ significantly from the rest, there maybe errors in the CSV due to mismatched columns (only the first batch of tweets determines what the header row is going to be). I haven't investigated this thoroughly, it may not be a problem unless people glued together datasets maybe.

**Comment by edsu** [comment]
Much improved @igorbrigadir I guess we could always hard code a list of expected columns. Shifting number of columns could be difficult to notice, and could lead to some pretty serious analysis problems.

**Comment by osemele** [comment]
Thanks for the upgrade, however, a 2gb jsonl file I am trying to convert to csv is taking 4hrs and more to run without completion. However, smaller files below 200mb successfully convert to csv within 5mins.
I have upgraded twarc-csv, what else could be the problem, and what can i do?

**Comment by igorbrigadir** [comment]
Following up in #12
