### ISSUE TITLE
collecting data based on specific list of usernames. 

### ISSUE THREAD

**Issue by unipdjahanifar** [DocNow/twarc-csv#49]
Hello,
I am collecting data for research, and I have an inquiry. If someone can help me, I will be appreciated it. Could you please let me know whether it is possible to pass a list of supreme leaders’ usernames and the president’s usernames of countries into the twarc2 and collect the data with a specific keyword?

**Comment by edsu** [comment]
Do you want to search within the tweets that these users authored? How many users are we talking about here?

**Comment by unipdjahanifar** [comment]
Hello, Yes. 
I want to search within the tweets of presidents of all countries (suppose around 190 users) with the climate change keyword; then, I want to make a network with the twarc2 network.

**Comment by igorbrigadir** [comment]
Yes, if you generate a text file that contains something like this, 1 query per line `input.txt` :

```
from:account1 ("climate change" OR #ClimateEmergency OR #COP26 OR ...)
from:account2 ("climate change" OR #ClimateEmergency OR #COP26 OR ...)
...
```

And now you can use:

```
twarc2 searches input.txt output.jsonl
```

And then `twarc2 network` depending on what you want to extract.

**Comment by igorbrigadir** [comment]
Feel free to follow up in https://github.com/DocNow/twarc/discussions or https://twittercommunity.com/
