### ISSUE TITLE
twarc2 search --limit inqueries 

### ISSUE THREAD

**Issue by unipdjahanifar** [DocNow/twarc-csv#50]
Hello,
would you mind to let me know, while I use the twarc2 search --limit, do the collected tweets are based on random search or based on specific algorithm?

**Comment by edsu** [comment]
This question isn't really relevant for the twarc-csv module, which simply converts tiwtter json to csv. Instead, please ask questions like this over in the twarc github [issue tracker](https://github.com/DocNow/twarc/issues) or, even better, the [discussions](https://github.com/DocNow/twarc/discussions) area. Thanks!
