### ISSUE TITLE
Add new fields for edited tweets

### ISSUE THREAD

**Issue by igorbrigadir** [DocNow/twarc-csv#52]
See https://github.com/DocNow/twarc/pull/657

**Comment by alexdatadesign** [comment]
Temporary workaround is to init with:

```
DataFrameConverter(
        extra_input_columns='edit_history_tweet_ids,edit_controls.edits_remaining,edit_controls.editable_until,edit_controls.is_edit_eligible' 
)

**Comment by lwrubel** [comment]
Tip for anyone using the plugin until this is added is to do the following:

```twarc2 csv tweets.jsonl tweets.csv --extra-input-columns edit_history_tweet_ids,edit_controls.edits_remaining,edit_controls.editable_until,edit_controls.is_edit_eligible```

**Comment by igorbrigadir** [comment]
Thanks! Should be fixed and in pypi in a few moments,

```
pip install --upgrade twarc-csv
```

That should update it!
