### ISSUE TITLE
ERROR: 4 - fails to transform a large JSONL file

### ISSUE THREAD

**Issue by reichaves** [DocNow/twarc-csv#53]
Hello
Please, I have a very large .jsonl file (870MB) and I am using python 3.8 on Ubuntu
But twarc csv fails to transform to CSVs:

twarc2 csv results.jsonl tweets_with_attacks_journalists.csv

💔 ERROR: 4 Unexpected items in data! 
Are you sure you specified the correct --input-data-type?
If the object type is correct, add extra columns with:
--extra-input-columns "edit_controls.is_edit_eligible,edit_controls.editable_until,edit_history_tweet_ids,edit_controls.edits_remaining"
Skipping entire batch of 9944 tweets!

Is there any other way to convert to CSV?

**Comment by igorbrigadir** [comment]
Fixed in `0.6.0`

Please update with:

```
pip install --upgrade twarc-csv
```

**Comment by mayuripandey** [comment]
Hi this worked before, but now its showing "100% 8.36k/8.36k [00:00<00:00, 169kB/s]

ℹ️
Parsed 1 tweets objects from 1 lines in the input file.
Write 1 rows and output 79 columns in the CSV."

Is there any changes that has been added, recently? Thanks in advance.
