### ISSUE TITLE
Duplicate tweets

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc-csv#6]
I noticed that when I collected a conversation, and then exported to CSV that I ended up with duplicate rows for tweets, presumably because they are included in other tweets. I'm not sure what the solution is here, but it definitely seems problematic from a usability perspective.

    twarc2 search conversation_id:1385008025140871168 > results.jsonl
    twarc2 csv results.jsonl > results.csv

then:

````python
>>> import pandas
>>> df = pandas.read_csv('results.csv')
>>> df.value_counts('id')
id
1385008025140871168    55
1385012190860611586     3
1385008825418321920     3
1385009576731422726     2
1385017514308956160     2
                       ..
1385015116987453441     1
1385015148184809474     1
1385015948273496068     1
1385018187419377665     1
1385192675549327366     1
Length: 68, dtype: int64
```

**Comment by igorbrigadir** [comment]
Yeah - this is a good point - i think the easiest thing to do is to keep a `set()` of ids and just use those to dedupe. I'll add this in.

**Comment by igorbrigadir** [comment]
There are now new options: `--allow-duplicates` to allow duplicate tweets in the CSV, and `--no-allow-duplicates` (default)
