### ISSUE TITLE
Extra checks for missing fields

### ISSUE THREAD

**Issue by igorbrigadir** [DocNow/twarc-csv#62]
When getting tweets with custom fields, twarc-csv will crash if those fields are missing, for example: 

```
line 277, in _process_entities
    if "cashtags" in entities:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by santoshbs** [comment]
I have the same issue:

```
in _format_tweet
    and "impression_count" not in tweet["public_metrics"]
```

Is there any workaround?

**Comment by igorbrigadir** [comment]
What's the twarc-csv version and full command / code you're running and do you have a sample of the tweets? Might be worth creating a separate issue! `impression_count` should be handled correctly if present (Set to None if it's missing)
