### ISSUE TITLE
Created_at

### ISSUE THREAD

**Issue by fuina** [DocNow/twarc-csv#64]
Hello! I would like to know if I could get as output-column the value "created_at". Thank you.

**Comment by igorbrigadir** [comment]
Yep! It's in there by default: https://github.com/DocNow/twarc-csv/blob/main/dataframe_converter.py#L25

To get a specific set of columns, you can specify them with comma separated list in `--output-columns` like:

```
twarc2 csv --output-columns "id,created_at" input.jsonl output.csv 
```
