### ISSUE TITLE
bookmark_count

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc-csv#65]
via DocNow Slack:

> When using twarc2 csv I am getting an error with this message: 

```
ERROR: 1 Unexpected items in data!
Are you sure you specified the correct --input-data-type?
If the object type is correct, add extra columns with:
--extra-input-columns "public_metrics.bookmark_count"
Skipping entire batch of 9526 tweets!
```

It looks maybe `public_metrics.bookmark_count`  should be added to the default set of properties so users don't trip up on it?

**Comment by igorbrigadir** [comment]
Sorry i missed this earlier! Adding this in now

**Comment by igorbrigadir** [comment]
Should be good to go now with `v0.7.2`
