### ISSUE TITLE
Escaped Unicode

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc-csv#7]
I noticed that unicode is JSON escaped in the CSV file. I think it should be converted to UTF-8 since it's no longer JSON?

    twarc search 👋 --flatten > wave.jsonl
    twarc csv wave.jsonl

**Comment by igorbrigadir** [comment]
The idea was to keep the text the same as the API, to make sure that the CSV is definitely valid - but i can see how this might be introducing some extra unwanted processing requirements.

I'll test out some larger datasets, and if it breaks and requires extra stuff it might make sense to keep it json encoded and let people deal with it themselves, but if it's largely parsing ok, it's an extra thing that can be removed.

**Comment by igorbrigadir** [comment]
In the new version I've added new options for this:

`--json-encode-all` if you want to encode everything
`--json-encode-lists` if you want to encode lists like entities and annotations - this makes it easier to parse them in some cases
`--json-encode-text` encodes tweet text, user descriptions

Default is to just encode the lists, but i'm open to suggestions on better defaults - or more options, or fewer.
