### ISSUE TITLE
Mixed column variables when converting from flattened search into csv

### ISSUE THREAD

**Issue by numeroteca** [DocNow/twarc-csv#9]
I've been downloading thousands tweets with search and flatten:
`twarc2 search 'xxx' --start-time 2018-03-20 --end-time 2018-04-30 --limit 2 --archive --flatten > xxx.jsonl`

When I convert to csv with `twarc2 csv`:
`twarc2 csv xxx.jsonl xxx.csv`

things seem to go well, but when I look into the column `author.username` is full of other strings of text that are not usernames:
`csvcut -c author.username xxx.csv`

such as date-time strings `2016-06-08T10:08:00.000Z`, ids `1604281548` or numbers `1186.0`.

If I look in one of the files exactly I see that problems start in line 6095:
![Screenshot from 2021-04-27 17-14-27](https://user-images.githubusercontent.com/1223722/116266866-2d233f00-a77c-11eb-90d3-1ec982f0ff5c.png)

when the variable `reply_settings` is filled with `[{"type": "retweeted", "id": "976557335748534273"}]`, and from there all the variable are mixed up.

When I make the same experiment with a few tweets from a short search, this problem is not there.

**Comment by igorbrigadir** [comment]
Does this happen with

`twarc2 csv --json-encode-text xxx.jsonl xxx.csv`

?

**Comment by edsu** [comment]
I wonder if this is related to https://github.com/DocNow/twarc-csv/issues/4#issuecomment-825259517 ?

**Comment by igorbrigadir** [comment]
Yes that could also be an issue - difficult to fix that and also support large files, but we can check for it an output an error - and maybe offer a manual way to define the columns (thinking out loud)

**Comment by igorbrigadir** [comment]
if possible, @numeroteca, could you send me the `xxx.jsonl` file somehow? Or maybe it's enough to post what `twarc2 search 'xxx'` is so i can reproduce this

**Comment by numeroteca** [comment]
@igorbrigadir, I tried with `--json-encode-text `:  `twarc2 csv --json-encode-text xxx.jsonl xxx.csv` and it throws the same error.

The original query was:
twarc2 search 'cifuentes' --start-time 2018-03-20 --end-time 2018-03-22 --archive --flatten > xxx.jsonl 

It's a 1,2GB file. I can upload it and send the link privately, sure. I am not being able to dehydrate the jsonl to provide the full list of ids. `twarc dehydrate xxx.jsonl > desidratado.txt` returns an empty file.  I also tried with a non flatten jsonl with the same results (that's another issue).

I like the idea of being able to select manually which columns to use. In fact that is the next piece of code I need, I used R for it:

```R
# Transform single file to select only some columns and save as "*_simple.csv"
path <- "../twarc/data/cifuentes/process/"
file <- "cifu_180326-180331.csv"
file_kern <- file %>% str_replace_all(".csv","")

data_twarc <- read.delim( paste0(path,file), sep = ",") %>% select(
  # select only useful columns
  id, created_at, author.username, text,source,type, author.created_at, entities.urls
  ) %>% mutate(
    time = as.POSIXct( substr( str_replace_all( created_at, "T"," "), 1,19 ), format="%Y-%m-%d %H:%M:%S", tz="UTC", start= as.Date("1970-01-01") )
  ) %>% arrange(time) 
write.csv(data_twarc, file =  paste0(path,file_kern,"_simple.csv") , row.names = FALSE)
```

**Comment by igorbrigadir** [comment]
I released a new version with lots of fixes, update the script:

```
pip install --upgrade twarc-csv
```

and run `twarc2 csv` again.

Please reopen if there are any more errors!

**Comment by numeroteca** [comment]
Thanks so much for the quick fix!

**Comment by numeroteca** [comment]
For the record. @congosto has just released this script [twarc2thoarder.py](https://github.com/congosto/t-hoarder_kit/blob/master/scripts/twarc2thoarder.py) to flatten and convert to `tsv` a `twarc2 search` generated file. It formats it to the way t-hoarder, the software she develops. t-hoarder is python base script, that, like twarc, allows a friendly interaction with Twitter API.

[I've created a manual](https://github.com/congosto/t-hoarder/wiki/Convert-twarc2-json-file-to-t-hoarder-format-with-twarc2thoarder.py) to explain how it works and the differences with `twarc2 csv`, in case you are interested.
